title: all about software
email: br@reecon.at
description: >
  This blog is all about software development and project managment.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://blog.reecon.at" # the base hostname & protocol for your site
url: "http://breiting.github.io" # the base hostname & protocol for your site

author:
  name:    'Bernhard Reitinger'
  bio:     'Agile Software Consultant'
  email:   br@reecon.at
  disqus:  breitinggithubio

github_url: https://github.com/briting
github_username:  breiting
twitter_username: allaboutsoftware
google_analytics: UA-67802634-2

comments: true

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

gems:
    - jekyll-gist
